#!/usr/bin/env python
#
# This illustrates the call-flow required to complete an OAuth request
# against the discogs.com API. The script will download and save a single
# image from the discogs.com API as an example.
# See README.md for further documentation.
#
import oauth2 as oauth
import urlparse

# Your consumer key and consumer secret generated by discogs when an application is created
# and registered . See https://www.discogs.com/settings/developers . These credentials
# are assigned by application and remain static for the lifetime of your discogs application.
# the consumer details below were generated for the 'discogs-oauth-example' application.
consumer_key = 'JJCOegYnRLCLRejtcZbo'
consumer_secret = 'UFlGrCViqSkoBNfRTGZyUfmpTGNbFbMM'

# The following oauth end-points are defined by discogs.com staff. These static endpoints
# are called at various stages of oauth handshaking.
request_token_url = 'http://api.discogs.com/oauth/request_token'
authorize_url = 'http://www.discogs.com/oauth/authorize'
access_token_url = 'http://api.discogs.com/oauth/access_token'

# A user-agent is required with Discogs API requests. Be sure to make your user-agent
# unique, or you may get a bad response.
user_agent = 'discogs_api_example/1.0'

# create oauth Consumer and Client objects using
consumer = oauth.Consumer(consumer_key, consumer_secret)
client = oauth.Client(consumer)

# pass in your consumer key and secret to the token request URL. Discogs returns
# an ouath_request_token as well as an oauth request_token secret.
resp, content = client.request(request_token_url, 'POST', headers={'User-Agent': user_agent})

# we terminate if the discogs api does not return an HTTP 200 OK. Something is
# wrong.
if resp['status'] != '200':
    raise Exception('Invalid response {0}.'.format(resp['status']))

request_token = dict(urlparse.parse_qsl(content))

print ' == Request Token == '
print '    * oauth_token        = {0}'.format(request_token['oauth_token'])
print '    * oauth_token_secret = {0}'.format(request_token['oauth_token_secret'])
print

# Authorize our newly received request_token against the discogs oauth endpoint.
# Prompt your user to "accept" the terms of your application. The application
# will act on behalf of their discogs.com account.
# If the user accepts, discogs displays a key to the user that is used for
# verification. The key is required in the 2nd phase of authentication.
print 'Please browse to the following URL {0}?oauth_token={1}'.format(
        authorize_url, request_token['oauth_token'])

# Waiting for user input
accepted = 'n'
while accepted.lower() == 'n':
    print
    accepted = raw_input('Have you authorized me at {0}?oauth_token={1} [y/n] :'.format(
        authorize_url, request_token['oauth_token']))

# request the verification token from the user.
oauth_verifier = raw_input('Verification code :')

# Generate objects that pass the verification key with the oauth token and oauth
# secret to the discogs access_token_url
token = oauth.Token(request_token['oauth_token'], request_token['oauth_token_secret'])
token.set_verifier(oauth_verifier)
client = oauth.Client(consumer, token)

resp, content = client.request(access_token_url, 'POST', headers={'User-Agent': user_agent})

# if verification is successful, the discogs oauth API will return an access token
# and access token secret. This is the final authentication phase. You should persist
# the oauth_token and the oauth_token_secret to disk, database or some
# other local store. All further requests to the discogs.com API that require authentication
# and must be made with these access_tokens.
access_token = dict(urlparse.parse_qsl(content))

print ' == Access Token =='
print '    * oauth_token        = {0}'.format(access_token['oauth_token'])
print '    * oauth_token_secret = {0}'.format(access_token['oauth_token_secret'])
print ' Authentication complete. Future requests must be signed with the above tokens.'
print


# We're now able to fetch an image using the application consumer key and secret,
# along with the verified oauth token and oauth token for this user.
token = oauth.Token(key=access_token['oauth_token'],
        secret=access_token['oauth_token_secret'])
client = oauth.Client(consumer, token)
resp, content = client.request('http://api.discogs.com/image/R-40522-1098545214.jpg', 
        headers={'User-Agent': user_agent})

print ' == Authenticated API image request =='
print '    * response status      = {0}'.format(resp['status'])
print '    * saving image to disk = R-40522-1098545214.jpg'

with open('R-40522-1098545214.jpg', 'w') as fh:
    fh.write(content)
